# Generated by Django 5.0.7 on 2024-07-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=20)),
                ("course_description", models.CharField(max_length=20)),
                ("course_capacity", models.PositiveSmallIntegerField()),
                ("course_teacher_in_charge", models.CharField(max_length=20)),
                ("course_student_enrolled", models.PositiveSmallIntegerField()),
                ("course_start_time", models.CharField(max_length=20)),
                ("course_assessment_method", models.CharField(max_length=20)),
            ],
        ),
    ]
