# Generated by Django 5.0.7 on 2024-07-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=20)),
                ("class_capacity", models.PositiveSmallIntegerField()),
                ("class_teacher_in_charge", models.CharField(max_length=20)),
                ("class_number_of_groups", models.PositiveSmallIntegerField()),
                ("class_courses", models.PositiveSmallIntegerField()),
                ("class_description", models.PositiveSmallIntegerField()),
            ],
        ),
    ]
