# Generated by Django 5.0.7 on 2024-07-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("student_email", models.EmailField(max_length=20)),
                ("student_nationality", models.CharField(max_length=20)),
                ("student_date_of_birth", models.DateField()),
                ("student_code", models.PositiveSmallIntegerField()),
            ],
        ),
    ]
